accounts/urls.py
from django.urls import path
from accounts.views import *
from django.contrib.auth import views as auth_views


app_name = 'accounts'

urlpatterns = [
    #login
    #logout
    #registration / signup
    path('login', login_view, name = 'login'),
    path('logout', logout_view, name = 'logout'),
    path('signup', signup_view, name = 'signup'),
    path('change_password/', change_password, name='change_password'),
    path('password_change_done/', password_change_done, name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html',
            email_template_name='accounts/password_reset_email.html',
            subject_template_name='accounts/password_reset_subject.txt',
            success_url='/password_reset_done/'
        ), name='password_reset'),
        path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html',
            success_url='/password_reset_complete/'
        ), name='password_reset_confirm'),
    ]
    #path('test', test, name = 'test'),

blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed
app_name = 'blog'

urlpatterns = [
    path('', blog_view, name = 'index'),
    path('<int:pid>', blog_single, name = 'single'),
    path('category/<str:cat_name>', blog_view, name = 'category'),
    path('tag/<str:tag_name>', blog_view, name = 'tag'),
    path('author/<str:author_username>', blog_view, name = 'author'),
    path('search/', blog_search, name = 'search'),
    path("rss/feed/", LatestEntriesFeed()),

    #path('test', test, name = 'test'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from django.contrib.auth import views as auth_views
#import debug_toolbar

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path( "sitemap.xml", sitemap, {"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('accounts.urls')),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html'
        ), name='password_reset_done'),
        path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
        ), name='password_reset_complete'),
]
    
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


#class CustomUser(AbstractUser):
#    pass


# Create your models here.

accounts/forms.py
from django import forms
from django.forms.forms import Form
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms.fields import EmailField


class SignupForm(UserCreationForm):
    username = forms.CharField(label='Username', min_length=5,max_length=150)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    def username_clean(self):
        username = self.cleaned_data['username'].lower()
        new = User.objects.filter(username = username)
        if new.count():
            raise ValidationError('User Already Exist')
        return username
    
    def email_clean(self):
        email = self.cleaned_data['email'].lower()
        new = User.objects.filter(email = email)
        if new.count():
            raise ValidationError('Email Already Exist')
        return email
    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2 and password1 != password2 :
            raise ValidationError("Password don't match")
        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user
    

accounts/views.py
from django.shortcuts import render,redirect,HttpResponseRedirect
from django.contrib.auth import authenticate , login , logout 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from accounts.forms import SignupForm
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

def login_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            username = request.POST["username"]
            password = request.POST["password"]
            try:
                user = authenticate(request, username=User.objects.get(email=username), password=password)
            except:
                user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                messages.error(request, "Username Or Password is not valid")  
        return render(request,'accounts/login.html')
    else:
        return redirect('/')
@login_required()
def logout_view(request):
    logout(request)
    return redirect('/')
    #if request.user.is_authenticated:
    #    logout(request)
    #return redirect('/')

def signup_view(request):
    if not request.user.is_authenticated :
        if request.method == 'POST':
            form = SignupForm(request.POST)
            
            if form.is_valid():
                form.save()
                messages.success(request,'Account created successfully')
                return redirect('/accounts/login')
            else:
                messages.error(request,'Account did not create')

        form = SignupForm()
        context = {'form':form}
        return render(request,'accounts/signup.html',context)
    else :
        return redirect('/')

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # To keep the user logged in
            return redirect('password_change_done')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {'form': form})

def password_change_done(request):
    return render(request, 'accounts/password_change_done.html')
# Create your views here.

templates/accounts/change_password.html
{% extends "base_accounts.html" %}

{% block title %}Change Password{% endblock %}

{% block content %}
  <h2>Change Password</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change Password</button>
  </form>
{% endblock %}

templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="img js-fullheight">
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">Login </h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-4">
                    <div class="login-wrap p-0">
                        <h3 class="mb-4 text-center">Have an account?</h3>
                        {% include 'messages.html' %}
                        <form action="{% url 'accounts:login' %}" method="post" class="signin-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" name="username" class="form-control" placeholder="Username Or Email" required><br>
                                <input name="password" type="password" class="form-control" placeholder="Password" required><br>
                                <button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>
                            </div>
                            <div class="form-group d-md-flex">
<!-- Section remember me-->
<!--
                                <div class="w-50">
                                    <label class="checkbox-wrap checkbox-primary">Remember Me
                                        <input type="checkbox" checked>
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
-->
                                <div class="w-50 text-md-right">
                                    <a href="{% url 'accounts:password_reset' %}" style="color: #fff">Forgot Password</a>
                                </div>
                            </div>
                        </form>
                        
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script defer
        src="https://static.cloudflareinsights.com/beacon.min.js/v8b253dfea2ab4077af8c6f58422dfbfd1689876627854"
        integrity="sha512-bjgnUKX4azu3dLTVtie9u6TKqgx29RBwfj3QXYt5EKfWM/9hPSAI/4qcV5NACjwAo8UtTeWefx6Zq5PHcMm7Tg=="
        data-cf-beacon='{"rayId":"816af3b5ff735c38","version":"2023.8.0","b":1,"token":"cd0b4b3a733644fc843ef0b185f98241","si":100}'
        crossorigin="anonymous"></script>
</body>

</html>

templates/accounts/password_change_done.html
{% extends "base_accounts.html" %}

{% block title %}Password Changed{% endblock %}

{% block content %}
  <h2>Password Changed</h2>
  <p>Your password has been successfully changed.</p>
{% endblock %}

templates/accounts/password_reset_complete.html
{% extends 'base_accounts.html' %}
{% block title %}Password Reset Complete Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h4>Password Reset Complete Page</h4>
                    <hr>
                    <div class="alert alert-info">
                        Your password reset is successful. Log in with new credentials
                    </div>
                    <a href="{% url 'accounts:login' %}">Login</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends "base_accounts.html" %}

{% block title %}Reset Password{% endblock %}

{% block content %}
<section class="contact-page-area section-gap">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <form class="form-area contact-form text-right"  method="post">
          <p>Enter your new password below:</p>
          {% csrf_token %}
          {{ form.as_p }}
          <div class="row">
              <button class="genric-btn primary" style="float: right;" type="submit">Reset Password</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/accounts/password_reset_done.html
{% extends "base_accounts.html" %}

{% block title %}Password Reset Email Sent{% endblock %}

{% block content %}
<section class="contact-page-area section-gap">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h2>Password Reset Email Sent</h2>
        <p>We've sent you an email with instructions on how to reset your password. Please check your inbox.</p>
      </div>
    </div>
  </div>
</section>
  
  
{% endblock %}

templates/accounts/password_reset_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Reset</title>
</head>
<body>
    <p>Click the following link to reset your password:</p>
    <p><a href="http://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}">Reset Password</a></p>
    <p>If you didn't request a password reset, please ignore this email.</p>
</body>
</html>

templates/accounts/password_reset_form.html
{% extends "base_accounts.html" %}
{% load static %}

{% block title %}Password Reset{% endblock %}

{% block content %}
<section class="contact-page-area section-gap">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <form class="form-area contact-form text-right"  method="post">
          <p>Enter your email address to reset your password.</p>
          {% csrf_token %}
          {{ form.as_p }}
          <div class="row">
              <button class="genric-btn primary" style="float: right;" type="submit">Reset Password</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/accounts/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Sign UP</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="img js-fullheight">
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">Sign UP </h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-4">
                    <div class="login-wrap p-0">
                        {% include 'messages.html' %}
                        <h3 class="mb-4 text-center">Create an account?</h3>
                        <form action="{% url 'accounts:signup' %}" method="post" class="signin-form">
                            {% csrf_token %}
                            <div class="form-group justify-content-center" >
                                <table>
                                {{form.as_table}}
                                    <tr>
                                        <td></td>
                                    </tr>


                                </table>
                                <button type="submit" class="form-control btn btn-primary submit px-3">Sign Up</button>
                                <!--                 
                                <input type="text" name="username" class="form-control" placeholder="Username" required><br>
                                <input type="email" name="email" class="form-control" placeholder="Email address"  required
                                pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$" ><br>
                                <input name="password1" type="password" class="form-control" placeholder="Password" required><br>
                                <input name="password2" type="password" class="form-control" placeholder="Confirm Password" required><br>
                                     -->                                 
                            </div>
                            <div class="form-group d-md-flex">
<!-- Section remember me-->
<!--
                                <div class="w-50">
                                    <label class="checkbox-wrap checkbox-primary">Remember Me
                                        <input type="checkbox" checked>
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
-->
                                <div class="w-50 text-md-right">
                                    <a href="#" style="color: #fff">Forgot Password</a>
                                </div>
                            </div>
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script defer
        src="https://static.cloudflareinsights.com/beacon.min.js/v8b253dfea2ab4077af8c6f58422dfbfd1689876627854"
        integrity="sha512-bjgnUKX4azu3dLTVtie9u6TKqgx29RBwfj3QXYt5EKfWM/9hPSAI/4qcV5NACjwAo8UtTeWefx6Zq5PHcMm7Tg=="
        data-cf-beacon='{"rayId":"816af3b5ff735c38","version":"2023.8.0","b":1,"token":"cd0b4b3a733644fc843ef0b185f98241","si":100}'
        crossorigin="anonymous"></script>
</body>

</html>